# Generated by Django 3.2 on 2023-06-20 13:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteRecipe',
            new_name='Favorite',
        ),
    ]
